added actions:read

diff --git a/.github/workflows/snyk-terraform-scan.yml b/.github/workflows/snyk-terraform-scan.yml
--- a/.github/workflows/snyk-terraform-scan.yml
+++ b/.github/workflows/snyk-terraform-scan.yml
@@ -8,6 +8,7 @@ on:
 permissions:
   security-events: write
   contents: read
+  actions: read
 
 jobs:
   snyk-scan:
@@ -16,21 +17,44 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Run Snyk for terraform
+      # - name: Run Snyk for terraform
+      #   id: snyk
+      #   uses: snyk/actions/iac@master
+      #   continue-on-error: true
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   with:
+      #     args: >-
+      #       --sarif-file-output=terraform/terraform-snyk.sarif
+      #       --severity-threshold=high
+      #       --fail-on=all
+      #     file: terraform/
+
+      - name: Install Snyk CLI
+        uses: snyk/actions/setup@master
+
+      - name: Run Snyk IaC test
         id: snyk
-        uses: snyk/actions/iac@master
-        continue-on-error: true
+        run: |
+          snyk iac test terraform/ \
+          --sarif-file-output=terraform/terraform-snyk.sarif \
+          --severity-threshold=high \
+          --fail-on=all
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          args: >-
-            --sarif-file-output=terraform/terraform-snyk.sarif
-            --severity-threshold=high
-            --fail-on=all
-          file: terraform/
+
+      - name: Check SARIF exists
+        id: sarif-check
+        run: |
+          if [ -f terraform/terraform-snyk.sarif ]; then
+           echo "exists=true" >> "$GITHUB_OUTPUT"
+          else
+           echo "exists=false" >> "$GITHUB_OUTPUT"
+           exit 1
+          fi
 
       - name: Upload SARIF results
-        if: steps.snyk.outcome == 'failure'
+        if: steps.snyk.conclusion == 'success' && steps.sarif-check.outputs.exists == 'true'
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: terraform/terraform-snyk.sarif
